name: Security

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
    - cron: "0 6 * * 1"

permissions:
  contents: read

jobs:
  govulncheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: DeterminateSystems/determinate-nix-action@v3

      - name: Install devbox
        run: curl -fsSL https://get.jetify.com/devbox | bash -s -- -f

      - run: devbox run -- bash -c "cd sso && go run golang.org/x/vuln/cmd/govulncheck@latest ./..."

  npm-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - uses: DeterminateSystems/determinate-nix-action@v3

      - name: Install devbox
        run: curl -fsSL https://get.jetify.com/devbox | bash -s -- -f

      - run: devbox run -- bash -c "cd typescript && npm audit --audit-level=high"
